sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6.3.1'
before_install:
  # guessing this works vvv
  #- sudo apt-get install libgnome-keyring-dev,
  - npm i -g npm@^3.10.3
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
#addons:
 # apt:
  #  packages:
   #   - libgnome-keyring-dev
      # also guessing on this ^^^